AllCops:
  TargetRubyVersion: '2.7.6'
  NewCops: enable
  Exclude:
    - Rakefile
    - "rakelib/**/*"
    - "**/example/*"
    - "bin/instrumentation_generator"
    - "**/**/vendor/bundle/**/*"
Bundler/OrderedGems:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
# We probably want to figure out how to set this up for the organization
Gemspec/RequireMFA:
  Enabled: false
Layout/LineLength:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "**/*test.rb"
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Naming/FileName:
  Exclude:
    - '**/opentelemetry-*'
Style/Documentation:
  Exclude:
    - "**/test/**/*"
    - "**/*test*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "**/gemfiles/*"
Style/ModuleFunction:
  Enabled: false
Style/MultilineIfModifier:
  Exclude:
     - "**/test/**/*"
Style/RedundantRegexpEscape:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - "**/gemfiles/*"
Style/SlicingWithRange:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
